client_id: 3MVG9FS3IyroMOh4Jm80Nf3C83m_XwZH78h5caTGhZpxRn9XzM7zOD_A5EH5pINQRjc7pg7qMHnwhapc.vve2
client_secret: 6229546370605087481
host: test.salesforce.com
username: development@datafut.com.sandbox
password: datafut#1R7hggdUXqPZ3XbD45YjrwKdF
debugging: true
